[package]
authors = ["Chris West (Faux) <git@goeswhere.com>"]
name = "mid-tool"
version = "0.1.0"

[dependencies]
clap = "2.26.1"
error-chain = "0.10.0"
reqwest = "0.7.3"
tempfile-fast = "0.1.1"
time = "0.1"
xdg = "2.1"
zstd = "0.4.14"

[dependencies.casync-http]
path = "../../casync-rs/http"
